name       : gotop
version    : 3.0.0
release    : 1
source     :
    - https://github.com/cjbassi/gotop/archive/3.0.0.tar.gz : d5147080bb6057f0bf0900b38438e89aa066959c845bdd4c84a9c9fe478b176f
license    : AGPL-3.0
component  : system.utils
summary    : A terminal based graphical activity monitor inspired by gtop and vtop
description: |
    Another terminal based graphical activity monitor, inspired by gtop and vtop, this time written in Go!
networking : yes
builddeps  :
    - git
    - golang
build      : |
    make dist/gotop
install    : |
    install -Dm00755 dist/gotop $installdir/usr/bin/gotop
